# Config file for automatic testing at travis-ci.org

language: python

install:
  - pip install coveralls flake8 git+git://github.com/public/flake8-import-order@2a595f1#egg=flake8-import-order
python:
  - "2.7"

# command to install dependencies and run tests
script:
  # If we are a Pull request, check the changes introduced in it for pep8
  #
  # Or if we are just on a branch, work out what we've changed since we
  # branched off master
  - |
    set -e -o pipefail;
    if [ "$TRAVIS_PULL_REQUEST" != "false" ]
      then git diff $TRAVIS_COMMIT_RANGE | flake8 --diff;
      else git fetch -q origin master:origin/master && git diff origin/master... | flake8 --diff
    fi

  # Then run the tests
  - coverage run --source=bootstrap_cfn setup.py test

after_success:
  coveralls

